### ISSUE TITLE
Several issues have been closed without commits

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website#44]
Expected: issues closed with a comment or commit as a fix.

Outcome: issues closed without a fix or a comment.

**Comment by boardfish** [comment]
Issues were closed with comments. Please refrain from raising issues that shouldn't exist.

**Comment by ollie-nye** [comment]
@Aterfax This is an open source passion project. It's so far from your place to be able to say how the main contributor manages issues and what happens with them. Raise relevant and constructive issues by all means, but don't stir things up for no good reason. Even better, maybe contribute to something instead of just complaining about something that doesn't affect you?

**Comment by Aterfax** [comment]
This is a project generating a website for the society I happen to be treasurer for.

I asked other individuals yesterday to check the aforementioned issue for me.

If they were incorrect in seeing issues close without comment then so be it.

That said, I would still insist on closes with a comment or commit so future maintainers can understand why a certain decision has been made.

**Comment by ollie-nye** [comment]
Wouldn't it be a good idea to check something yourself, instead of handing off responsibility to someone else only to throw them under the bus when questioned about it? Could you identify what the issue in question was? Maybe the best place for asking why something was closed would have been in a comment on that ticket instead of a whole new one that doesn't achieve anything.

**Comment by Aterfax** [comment]
Boardfish is literally our website tech officer... his role is to develop and maintain it.

I raise an issue, to get an answer. I got an answer. Not seeing a problem here.

I asked and was told several issues vanished without a comment or commit.

I raise an issue to ask about it via my phone because searching through a bunch of issues on a phone is inconvenient.

I have no idea what the throwing under a bus comment is with reference to but again. The role is website tech, which comes with the aforementioned responsibility.
